### ISSUE TITLE
Element-wise kernels: Prefetch data needed for time stepping at the start?

### ISSUE THREAD

**Issue by ali-ramadhan** [ali-ramadhan/Oceananigans.jl#44]
Jumping the gun here but instead of accessing e.g. `model.tracers.T[i, j, k+1]` multiple times during a time step, can it be prefetched, i.e. `T_kp1 = model.tracers.T[i, j, k+1]`, and then reused multiple times? Would the value or the pointer need to be accessed?

The only reason to do this is performance gain. Will this work or will the code turn into spaghetti? Can some sort of compiler figure this stuff out for us?

**Comment by glwagner** [comment]
What do you mean by 'fetched'? Are you referring to memory movement from main memory to cache?

I don't know much about cache optimization, but I think a guideline is that nearby operations should be nearby in memory. For example, when looping over elements of an array `u[i]`, your machine will use a linear forecast to bring `u[i-1], u[i-2], u[i+1], u[i+2]` into the cache simultaneous to `u[i]`. This idea leads to the 'struct of arrays' optimization when running loops over the elements of many arrays simultaneously.

This may be useful:

https://software.intel.com/en-us/articles/memory-layout-transformations

**Comment by ali-ramadhan** [comment]
Yeah I think that's kind of what I was thinking, much more for the GPU though. Dunno what the final element-wise kernels will look like but if the kernels are shared with the CPU and GPU then I'm not sure how memory will be managed (would be nice to avoid handling GPU shared memory manually). I think you're right, we just want a "struct of arrays" optimization.

For what it's worth @christophernhill says that the MITgcm already does this, and it doesn't seem to noticeably boost performance.

**Comment by glwagner** [comment]
If you write a 'kernel' to execute on a GPU, you will be writing a computation that is probably more amenable to cache optimization than otherwise. This is because the kernel will perform an operation that is local in physical space. Your task then will essentially be to arrange arrays in memory so that physical locations are nearby in memory. 

I am not that surprised that this micro-optimization does not always bear fruit. Presumably it is sensitive to the particular details of the algorithm.

**Comment by glwagner** [comment]
For what it's worth, I do not think your code will turn into spaghetti. It is not the algorithm that you have to tweak here, it is the memory layout of the data.

This thread may be useful:

https://stackoverflow.com/questions/2179426/how-to-structure-data-for-optimal-speed-in-a-cuda-app

**Comment by ali-ramadhan** [comment]
Thanks for the useful link. That makes sense that it's all about efficient memory arrangement.

Since it's a micro-optimization I'll mark it as wontfix and revisit when we have a model that runs on GPUs.

**Comment by ali-ramadhan** [comment]
Closing as this would EXTREMELY messy, sounds like a bad idea that won't help much.
