### ISSUE TITLE
Fast GPU support using element-wise kernels and GPUifyLoops.jl

### ISSUE THREAD

**Issue by ali-ramadhan** [ali-ramadhan/Oceananigans.jl#49]
This is the highest priority issue for now.

**Comment by glwagner** [comment]
What kernels are you targeting?

I propose that you define a small number of kernels that can be interpreted as self-contained. For example, you can define separate kernels for momentum, temperature, salinity, and arbitrary passive tracers. This way an 'equation' can be built up from its components, and parts can be left out if desired --- for example, it may not be necessary to use salinity, or you may wish to add 30 passive tracers.

**Comment by ali-ramadhan** [comment]
Basically all the operators would need to be rewritten, but I think the method you're proposing is already how it's done. Basically we define `δx!`, `δy!`, `δz!`, `avgx!`, `avgy!`, and `avgz!` operators then everything else (momentum advection, tracer diffusion, etc.) is built on top of those. If the equation changes we would probably have to write a different `time_step!` function but otherwise all the operators can be reused as needed.

Tracers just use `div_flux!` and `κ∇²!` so yeah it'll be trivial to time step an arbitrary number of tracer fields (https://github.com/ali-ramadhan/Oceananigans.jl/issues/25).

Just linking to some related posts regarding this issue:
* [Writing fast stencil computation kernels that work on both CPUs and GPUs](https://discourse.julialang.org/t/writing-fast-stencil-computation-kernels-that-work-on-both-cpus-and-gpus/20200)
* https://github.com/vchuravy/GPUifyLoops.jl/issues/12

**Comment by glwagner** [comment]
It looks to me that at the moment, the 'equation' is implemented intertwined with the Adams-Bashforth time-stepping method in the single function `time_step!`. Right? If we want to run a problem without salinity, we have to duplicate the entire `time_step!` and delete the part that operates on salinity.

I am proposing that, moving forward with the new paradigm, that separate fused kernels (functions) be written for each equation so that execution can be managed via multiple-dispatch (independent of the time-stepping method employed), rather than fusing an entire equation set into a single loop.

**Comment by ali-ramadhan** [comment]
Yes, you're right. The current setup is not ideal. Although I'm hoping that once #25 is implemented (it should be pretty easy) then the time stepping will loop over all tracers and time step them individually. That way if you want salinity it's added to the model, otherwise it's not included to begin with. I suppose you can leave out temperature as well, but then you'd have constant buoyancy everywhere...

Ah I see what you're saying. So have a more generic time stepping loop that basically time steps any equation we'd like to implement (e.g. rotating incompressible Boussinesq, quasi-geostrophic, etc.) using whatever numerics we'd like (e.g. 2nd vs. 4th order advection scheme, Adams–Bashforth vs. RK45). That would be a beautiful abstraction of a PDE solver. Let me know if I've misunderstood your point.

**Comment by glwagner** [comment]
Yes to more generic time-stepping!

There is some complexity in the time-stepping associated with the pressure correction. I cannot tell from looking at the code whether that aspect prevents generalization or not. 

If not, it is not a big deal. You can implement 'generic' time-stepping that always employs a pressure correction step, perhaps.

**Comment by ali-ramadhan** [comment]
Yeah I think the current time stepping algorithm (essentially what the MITgcm does) is pretty custom so it's probably not shared by other equations/methods, but the pressure correction step is pretty common to finite volume Navier-Stokes solvers and it should be possible to generalize it.

I'm thinking it might be good to tackle "generic time stepping" in two steps. 1. Getting the current version of the time stepping algorithm running efficiently on GPUs for milestone v0.4 and then 2. we can redesign for v0.5 and include more generic time stepping.

**Comment by jm-c** [comment]
just a comment: pressure correction (as done now) is just one piece of an implicit in time
component of the time stepping. The more general form would be: explicit part (AB or RK or just 
simple forward) then implicit part (including: pressure correction, implicit vertical for 
diffusion/viscosity or/and advection, implicit relaxation/damping).

**Comment by ali-ramadhan** [comment]
Ah right I didn't think of it that way, thanks! Might make the time stepping look cleaner if we make it clearly mark the explicit and implicit parts? I guess it might be arbitrary as the implicit pressure correction step is followed by an explicit time step.

**Comment by glwagner** [comment]
Building on what @jm-c said, I think we want to design an interface in which an equation is expressed as something like 

```
φ_t = Lφ + Ν(φ)
```

where `φ` is the solution (an array of fields in this case, probably), `L` is a linear operator that can be treated implicitly (depending on the time-stepping scheme), and `N(φ)` is a nonlinear operator.

The challenge is including the pressure correction in this paradigm. I think it should be possible --- we may just have to consider only time-steppers that invoke the special pressure correction substep.

I think the design should be about more than just 'marking' the terms. We can tackle the problem of designing a time-stepper to step forward an equation of a certain form completely independent from the development of an algorithm to calculate nonlinear terms, pressure corrections, and linear terms for a specific kind of equation. Then we put the pieces together to solve the problem.

**Comment by ali-ramadhan** [comment]
That would feel very clean and generic, sounds like a great idea. Would you mind copy pasting this into a new issue? This one will be closed by #54
