### ISSUE TITLE
Current Field structs are pretty unintuitive to use...

### ISSUE THREAD

**Issue by ali-ramadhan** [ali-ramadhan/Oceananigans.jl#5]
@glwagner Mostly a couple of notes of where I was in case you're thinking of working on the abstractions:

Currently `Field` is a struct with an `f::Array` in them, and are collected together in a struct of type `FieldCollection`. This kind of sucks because to create a new set of velocity + tracer fields and set the surface temperature field to 300 K for example, the code looks like:
```
using OceanDispatch
g = RegularCartesianGrid((100, 100, 50), (2000, 2000, 1000), Float64)
fs = Fields(g)
fs.θ.f[:, :, 1] .= 300
```
when I think it would be much more intuitive to be able to just write `fs.θ[:, :, 1] .= 300`.

**Comment by glwagner** [comment]
Your suggestion is easily achieved by defining a `getindex` method for objects of type `Field`. For example:

```
import Base: getindex

getindex(f::Field, inds...) = getindex(f.f, inds...)
```

I am refactoring `fields.jl` right now and implementing something essentially like (but slightly different).

Ultimately I think a nice API will relieve the user of interacting with the data arrays at all. For example, the correct way to set temperature could be something like 

```
set_surface_temperature!(model, 300)
```

**Comment by ali-ramadhan** [comment]
Oh yeah that should work. I'll wait and see what your implementation looks like then. I agree that something like `set_surface_temperature!(model, 300)` looks much more user-friendly and portable!

**Comment by ali-ramadhan** [comment]
`size, length, getindex, lastindex, setindex!`, and `iterate` functions are now defined for the abstract `Field` type so we should be good to go here.
