### ISSUE TITLE
CI testing for GPU code.

### ISSUE THREAD

**Issue by ali-ramadhan** [ali-ramadhan/Oceananigans.jl#53]
Right now easiest thing to do would be to manually test the package on Supercloud or somewhere with multiple GPUs, but CI with GPUs would be nice.

See for ideas: https://github.com/JuliaGPU/gitlab-ci

Might not be worth setting up for a while, seems like too much work.

**Comment by glwagner** [comment]
@navidcy may have some advice for setting up CI with GPUs.

A stopgap idea is to ask reviewers of pull requests to test the code to be pushed manually.

**Comment by vchuravy** [comment]
Let me know if I can help with setting up CI, the JuliaGPU infrastructure is quite painless and we should have enough capacity to let you borrow some compute.

**Comment by ali-ramadhan** [comment]
That would be awesome! Wasn't sure if it open to packages outside of Julia main framework. Just signed up on GitLab and requested access.

Looks like @navidcy is already a member, was FourierFlows.jl using this?

**Comment by ali-ramadhan** [comment]
GitLab CI is up and running. The build fails there but I think we've addressed this issue.

Resolved by https://github.com/ali-ramadhan/Oceananigans.jl/commit/228cc2e1d7a3e530d992b0e9ec79f999777b5ce6

**Comment by navidcy** [comment]
@ali-ramadhan, indeed I tried to use Gitlab CI with FourierFlows but I never managed to have it running. Then we did a major refactor of FourierFlows and the GPU functionality moved to CuFourierFlows.jl. We need to get back to it...
