### ISSUE TITLE
Running with Float32 leaves numerical artifacts.

### ISSUE THREAD

**Issue by ali-ramadhan** [ali-ramadhan/Oceananigans.jl#55]
Using 32-bit floats leaves numerical artifacts. See attached images of deep convection: top is surface temperature and bottom is vertical slice through the center of the cooling disk at time step 1500. They appear when using 32-bit floats on the CPU and GPU. I suspect the Poisson pressure solve is to blame. There are [things we can consider](http://www.fftw.org/accuracy/comments.html) to increase the accuracy of the FFT at single-precision. 

Float64 on CPU (good):
![64bit cpu](https://user-images.githubusercontent.com/20099589/52955264-36bdea80-335a-11e9-91ee-c58cbd19a3e5.png)

Float32 on CPU (bad):
![32bit cpu](https://user-images.githubusercontent.com/20099589/52955316-59e89a00-335a-11e9-9950-1f0bcd1f08ac.png)

Float32 on GPU (even worse, but still stable!):
![32bit gpu](https://user-images.githubusercontent.com/20099589/52955343-68cf4c80-335a-11e9-8bcb-7c533c369230.png)

**Comment by ali-ramadhan** [comment]
This might be an issue unless we scale units, etc.
`eps(Float32) = 1.1920929f-7`
` eps(Float64) = 2.220446049250313e-16`

**Comment by glwagner** [comment]
What happens when you double the resolution with `Float32`?

**Comment by ali-ramadhan** [comment]
It blows up so it must be worse, but trying again for fewer time steps to see what it looks like.

**Comment by ali-ramadhan** [comment]
Float32 on GPU (at time step 1000 instead of 1500). Temperature field looks correct except for all the noise and artifacts.
![float32 gpu 256x256x128 time_step_1000](https://user-images.githubusercontent.com/20099589/53046523-3c045d80-345e-11e9-8858-3f88c8ca3573.png)

@jm-c suggested it might be due to certain terms in the source terms being much larger/smaller than others.

Will further investigate this issue once #56 is resolved.

**Comment by glwagner** [comment]
This may be a caveat about attempting to solve fluids problems with single precision. For example [these authors](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.85.036315) report issues running two-dimensional turbulence simulations at single precision.

You may ameliorate issues with round-off error and finite precision by perhaps using a different (non-)dimensionalization of the equations of motion, parmaeters, and initial conditions.

**Comment by ali-ramadhan** [comment]
Yeah there are definitely situations where 64-bit precision is necessary (thinking continental slopes in an ocean model) but I think we were hoping it won't bite us too much for these horizontally periodic flat-bottom domains.

I think if we can't find an easy fix we can just do the Poisson solve using 64-bit precision and then convert back to 32-bit for the time stepping.

**Comment by ali-ramadhan** [comment]
Hmmm, this happens even with Float64 on the GPU.

Actually may be a bug in CuArrays.jl so I filed a pull request that might help with this issue: https://github.com/JuliaGPU/CuArrays.jl/pull/289

**Comment by ali-ramadhan** [comment]
Looks like it was the `cu(xs)` always returning `CuArray{Float32}` which I think we should never use.

Will switch to `Float64` for now and worry about this factor of 2 in performance and memory usage later.

**Comment by glwagner** [comment]
I don't know of any fluids codes that use single precision for research. It'd be good to know if this route has been pursued successfully before devoting significant effort to it.

**Comment by ali-ramadhan** [comment]
Slight update: Things look good if we use `Float32` for the time stepping and `Float64` for the global pressure solve.

**Comment by glwagner** [comment]
@ali-ramadhan is this still true even after we updated the algorithm to more strictly enforce incompressibility?
