### ISSUE TITLE
IDCT for dim=3 in 3D Poisson solver does not work on the GPU.

### ISSUE THREAD

**Issue by ali-ramadhan** [ali-ramadhan/Oceananigans.jl#56]
I could not get the Poisson pressure solver to work on the GPU. Most of it works but CUDA does not have a DCT function so I had to perform the DCT/IDCT in terms of the FFT/IFFT.

The DCT/IDCT functions work in isolation (regression tested with `FFTW.r2r!`, see link to Jupyter notebook below) but not in the Poisson solver. More specifically, the IDCT fails when applied to the third dimension (after or before the IFFT is applied to dimensions 1 and 2).

For now I got around this by copying the right hand side to the CPU, doing the transform on the CPU, and copying the geopotential back to the GPU. This operation is so much slower than the time stepping that it takes up like 98%+ of wall clock time. It might also be introducing further numerical errors.

Link to current Poisson GPU solver:
https://github.com/ali-ramadhan/Oceananigans.jl/blob/93aa0038b3126470f263475d648bceb9562bbe91/src/spectral_solvers.jl#L421

Messy Jupyter notebook: [Testing DCT/IDCT on the GPU](https://github.com/ali-ramadhan/random-jupyter-notebooks/blob/master/Oceananigans.jl/DCT%2BIDCT%20from%20DFT%2BIDFT.ipynb)

Messy Jupyter notebook: [Testing GPU Poisson solver](https://github.com/ali-ramadhan/random-jupyter-notebooks/blob/master/Oceananigans.jl/GPU/Testing%20GPU%20Poisson%20solver.ipynb)

**Comment by christophernhill** [comment]
@ali-ramadhan could the NVidia cufftw interface help ( https://docs.nvidia.com/cuda/cufft/index.html#fftw-supported-interface ) as a step. My reading is that this does things on GPU, so could avoid copy, but may not be as super optimal as native cuFFT. Maybe you already tried that - the advertising on the box seems to imply you just switch a few headers, link and existing FFTW works, but maybe there is small print?

**Comment by ali-ramadhan** [comment]
Yes I believe I was using the FFTW interface to do the FFT/IFFTs on the GPUs.

Where I got stuck is that the existing solver uses `FFTW.r2r!(f.data, FFTW.REDFT10, 3)` for the DCT and `FFTW.r2r!(ϕ.data, FFTW.REDFT01, 3)` for the IDCT, but under the "FFTW Interface to cuFFT" table, Read-to-Real Transforms and Read-to-Real Transform Kinds are "Not supported".

So I implemented a DCT using the N FFT ([following this post](https://dsp.stackexchange.com/a/10606))
https://github.com/ali-ramadhan/Oceananigans.jl/blob/93aa0038b3126470f263475d648bceb9562bbe91/src/spectral_solvers.jl#L359-L370

and an IDCT using the IFFT ([following these course notes](http://fourier.eng.hmc.edu/e161/lectures/dct/node2.html))
https://github.com/ali-ramadhan/Oceananigans.jl/blob/93aa0038b3126470f263475d648bceb9562bbe91/src/spectral_solvers.jl#L372-L387

They work in isolation (they produce the same output as `FFTW.r2r!` but do not work when I substitute them into the Poisson solver. I'm playing around with it right now, hoping it's just a bug on my part.

**Comment by ali-ramadhan** [comment]
Hmmm, now I look through the notes again, maybe the IDCT I implemented only works for real inputs. I'll keep playing around.

**Comment by ali-ramadhan** [comment]
Upon closer inspection of the [REDFT01 (DCT-III) transform](http://www.fftw.org/fftw3_doc/1d-Real_002deven-DFTs-_0028DCTs_0029.html) in FFTW, I should have been dividing the first element _X₀_ by 2 in our DCT-III implementation using the IFFT. The correct IDCT is thus
```julia
function idct_dim3_gpu!(f)
    Nx, Ny, Nz = size(f)
    
    bfactors = exp.(collect(1im*π*(0:Nz-1) / (2*Nz)))
    bfactors[1] *= 0.5

    f .*= cu(repeat(reshape(bfactors, 1, 1, Nz), Nx, Ny, 1))
    ifft!(f, 3)
    
    f .= cu(reshape(permutedims(cat(f[:, :, 1:Int(Nz/2)], f[:, :, end:-1:Int(Nz/2)+1]; dims=4), (1, 2, 4, 3)), Nx, Ny, Nz))
    # @. f = real(f)  # Don't do it here. We'll do it when assigning real(ϕ) to pNHS to save some measly FLOPS.
    
    nothing
end
```
This can all be optimized, but at least a working Poisson solver is a good step.
