### ISSUE TITLE
Horizontal and vertical transforms

### ISSUE THREAD

**Issue by glwagner** [ali-ramadhan/Oceananigans.jl#6]
The wavenumber and transforms are being worked on.

@ali-ramadhan, see here for how FourierFlows.jl constructs wavenumbers:

https://github.com/FourierFlows/FourierFlows.jl/blob/master/src/domains.jl#L130

I think it makes sense to do the `r2r` transform in `z` first. That way you can take advantage of the realness of your output in the subsequent horizontal transform.

For the 2D horizontal transform, you can use the 2D `rfft`. If your input array is `nx, ny`, the 2D rfft will output an array of size `nx/2+1, ny` --- using a real transform + conjugate form for the transform along `x` (the first dimension), and a full transform along `y` (since after transforming along `x`, your quantities are no longer real). 

Hopefully this makes sense. Let me know if you have questions.

Ultimately I believe it will be best to use a tridiagonal solve in the vertical + Fourier transforms in the horizontal to permit arbitrary vertical grids for similar computational cost (but slightly more complex algorithm).

**Comment by ali-ramadhan** [comment]
Thanks for the info @glwagner!

I decided to go back and build up the spectral solver from the 1D case which now works  using `rfft` and `irfft` as tested against analytic solutions, and I discovered a couple of bugs with my 3D solver in the process. Working on the 2D solver now and this issue + [`domains.jl`](https://github.com/FourierFlows/FourierFlows.jl/blob/master/src/domains.jl#L130) will be quite helpful.

**Comment by glwagner** [comment]
Great, keep us updated!

**Comment by ali-ramadhan** [comment]
Got the 1D and 2D solvers working and confirmed that they converge spectrally using your 2D wavenumber construction. Here are the tests you've been craving: [`test_spectral_solvers.jl`](https://github.com/ali-ramadhan/OceanDispatch.jl/blob/fixing-nonhydrostatic-algorithm/test/test_spectral_solvers.jl)

**Comment by ali-ramadhan** [comment]
This has been figured out. We have
1. `solve_poisson_3d_ppn(f, Nx, Ny, Nz, Δx, Δy, Δz)`
2. `solve_poisson_3d_ppn!(g::RegularCartesianGrid, f::CellField, ϕ::CellField)`
3. `solve_poisson_3d_ppn_planned!(ssp::SpectralSolverParameters, g::RegularCartesianGrid, f::CellField, ϕ::CellField)`

that work and pass multiple tests. The DCT is slower than the FFT (somewhat expected) and for some reason we couldn't get it to work with `FFTW.rfft` but those are optimizations we can figure out later.
