### ISSUE TITLE
GPU sections should only execute on CUDA-enabled machines.

### ISSUE THREAD

**Issue by ali-ramadhan** [ali-ramadhan/Oceananigans.jl#62]
Right now it won't run on a computer without CUDA and is also why Travis CI builds are erroring.

A quick hack would be to do something like what CliMA does:
```julia
const HAVE_CUDA = try
  using CUDAdrv
  using CUDAnative
  true
catch
  false
end


macro hascuda(ex)
  return HAVE_CUDA ? :($(esc(ex))) : :(nothing)
end

 @hascuda device!(MPI.Comm_rank(mpicomm) % length(devices()))
```

**Comment by vchuravy** [comment]
Would be good to have something like that in GPUifyLoops, to get rid of that annoying boilerplate

**Comment by ali-ramadhan** [comment]
Resolved by https://github.com/ali-ramadhan/Oceananigans.jl/commit/63e26bb7b9d8d472aa6b484b9fd6e482154cb422
