### ISSUE TITLE
circshift question

### ISSUE THREAD

**Issue by christophernhill** [ali-ramadhan/Oceananigans.jl#9]
@ali-ramadhan this looks odd to me
https://github.com/ali-ramadhan/OceanDispatch.jl/blob/c4aaa79323008270294d9052c088da7ddaf47fb2/src/operators.jl#L34

if I do 
```
  julia> a=Vector(1:4);circshift(a,1)
```
I get
```
4-element Array{Int64,1}:
 4
 1
 2
 3
```

doesn't this mean that 
```
δˣ(f) = (f .- circshift(f, (1, 0, 0)))
```

is more intuitively

```
δˣ(f) = (circshift(f, (1, 0, 0)) .- f)
```

**Comment by christophernhill** [comment]
oops - I typed a -1 by mistake! 

Looks good!!!

**Comment by ali-ramadhan** [comment]
No worries, thanks for checking through it!

The `δˣ` operator has been deprecated in some sense in favor of `δˣz2f` and `δˣf2z` for now which know about cell centers and cell faces. Once the nonhydrostatic algorithm works and I can refactor it nicely they'll just become `δˣz2f!` and `δˣf2z!`.
